services:
  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api-gateway/.env
    networks:
      - microservice-network
    depends_on:
      - identity-service
      - transaction-service
      - ocr-service
      - budget-notification-service

  identity-service:
    build:
      context: .
      dockerfile: identity-service/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./identity-service/.env
    networks:
      - microservice-network

  transaction-service:
    build:
      context: .
      dockerfile: transaction-service/Dockerfile
    ports:
      - "3002:3002"
    env_file:
      - ./transaction-service/.env
    networks:
      - microservice-network

  ocr-service:
    build:
      context: .
      dockerfile: ocr-service/Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./ocr-service/.env
    networks:
      - microservice-network

  budget-notification-service:
    build:
      context: .
      dockerfile: budget-notification-service/Dockerfile
    ports:
      - "3004:3004"
    env_file:
      - ./budget-notification-service/.env
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
